const state = { Vlink: "", language: "en", history: [], lastTutorMessage: "" };
const stage = document.querySelector(".stage"), text = document.getElementById("tutor-text"), input = document.getElementById("message"), status = document.getElementById("status"), suggestions = document.getElementById("suggestions"), mic = document.getElementById("microphone"), voiceLabel = document.getElementById("voice-label"), composer = document.getElementById("composer");
function key() { return `practice_history_${btoa(unescape(encodeURIComponent(state.Vlink))).slice(0, 80)}`; }
function save() { if (state.Vlink) localStorage.setItem(key(), JSON.stringify({ language: state.language, history: state.history })); }
function showTutor(message) { state.lastTutorMessage = message; text.textContent = message; }
function add(role, message) { state.history.push({ role, text: message }); save(); if (role === "tutor") showTutor(message); }
function setSuggestions(items = []) { suggestions.innerHTML = ""; items.slice(0, 3).forEach(item => { const button = document.createElement("button"); button.type = "button"; button.textContent = item; button.onclick = () => send(item); suggestions.append(button); }); }
function closeWriter() { composer.hidden = true; stage.classList.remove("is-writing"); }
async function loadPractice(vlink) { state.Vlink = String(vlink || "").trim(); if (!state.Vlink) { showTutor("Your practice is loading. Please wait a moment."); return; } try { const stored = JSON.parse(localStorage.getItem(key()) || "{}"); state.language = stored.language || "en"; state.history = Array.isArray(stored.history) ? stored.history : []; const response = await fetch("/practice/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ Vlink: state.Vlink }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load practice."); setSuggestions(data.suggestions); const last = [...state.history].reverse().find(item => item.role === "tutor"); if (last) showTutor(last.text); else add("tutor", data.opening); status.textContent = ""; } catch (error) { showTutor("I cannot load this practice right now."); status.textContent = error.message; } }
async function send(value) { const message = String(value || input.value).trim(); if (!message) return; if (!state.Vlink) { status.textContent = "The activity link is still loading."; return; } add("student", message); input.value = ""; closeWriter(); status.textContent = "Thinking…"; try { const response = await fetch("/practice/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ Vlink: state.Vlink, message, language: state.language, history: state.history.slice(-8) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to answer."); state.language = data.language || state.language; add("tutor", data.reply); status.textContent = ""; } catch (error) { status.textContent = error.message; } }
composer.addEventListener("submit", event => { event.preventDefault(); send(); });
document.getElementById("write").onclick = () => { const opening = composer.hidden; composer.hidden = !opening; stage.classList.toggle("is-writing", opening); if (opening) input.focus(); };
document.getElementById("close-writer").onclick = closeWriter;
document.getElementById("help").onclick = () => document.getElementById("help-dialog").showModal();
document.getElementById("close-help").onclick = () => document.getElementById("help-dialog").close();
document.getElementById("listen").onclick = () => { speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(state.lastTutorMessage); utterance.lang = state.language === "es" ? "es-ES" : "en-US"; speechSynthesis.speak(utterance); };
const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
if (Recognition) { const recognition = new Recognition(); recognition.interimResults = false; recognition.continuous = false; recognition.onstart = () => { mic.classList.add("is-listening"); voiceLabel.textContent = "Listening…"; status.textContent = ""; }; recognition.onresult = event => { voiceLabel.textContent = "Sending your answer…"; send(event.results[0][0].transcript); }; recognition.onerror = event => { mic.classList.remove("is-listening"); voiceLabel.textContent = "Press to speak"; status.textContent = event.error === "not-allowed" ? "Microphone permission is required." : "I could not hear that. Please try again."; }; recognition.onend = () => { mic.classList.remove("is-listening"); if (!status.textContent) voiceLabel.textContent = "Press to speak"; }; mic.onclick = async () => { try { if (navigator.mediaDevices?.getUserMedia) { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.getTracks().forEach(track => track.stop()); } recognition.lang = state.language === "es" ? "es-ES" : "en-US"; recognition.start(); } catch { status.textContent = "Microphone permission is required."; } }; } else mic.onclick = () => status.textContent = "Speech recognition is not available in this browser.";
function receive(data) { const vlink = data?.Vlink || data?.vlink || data?.datos?.Vlink || data?.datos?.vlink; if (vlink) loadPractice(vlink); }
window.recibirDatosStoryline = receive; window.cargarVlink = loadPractice; window.addEventListener("message", event => { if (event.data?.type === "practice-vlink" || event.data?.type === "STORYLINE_CONTEXT") receive(event.data); }); window.addEventListener("DOMContentLoaded", () => { const vlink = new URLSearchParams(location.search).get("Vlink"); if (vlink) loadPractice(vlink); else showTutor("Hi! Your guided conversation will begin in a moment."); });
